/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Usuario;
import Logica.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaby Verdugo
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public RegistrarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private boolean ValidacionesIngreso()
    {
        boolean estado = true;
        
        if(RegistroNombre.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Ingrese el nombre de usuario.");
            estado = false;
        }
        
        if(RegistroPassword.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Ingrese una contraseña.");
            estado = false;
        }
        else
        {
            if(RegistroPassword.getText().length()<6)
            {
                JOptionPane.showMessageDialog(null,"Ingrese una contraseña de almenos 6 caracteres.");
                estado = false;
            }
        }
        
        return estado;
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFondoRegistro = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombreR = new javax.swing.JLabel();
        jLabelPasswordR = new javax.swing.JLabel();
        jLabelCorreoR = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        RegistroNombre = new javax.swing.JTextField();
        RegistroPassword = new javax.swing.JPasswordField();
        RegistroCorreo = new javax.swing.JTextField();
        RegistroCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombreR2 = new javax.swing.JLabel();
        jLabelFondoRegistro1 = new javax.swing.JLabel();

        jLabelFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(153, 204, 255));
        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 102, 204));
        jLabelTitulo.setText("Registro de Usuario");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabelNombreR.setBackground(new java.awt.Color(255, 51, 0));
        jLabelNombreR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNombreR.setForeground(new java.awt.Color(0, 102, 204));
        jLabelNombreR.setText("Nombre :");
        getContentPane().add(jLabelNombreR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabelPasswordR.setBackground(new java.awt.Color(255, 51, 0));
        jLabelPasswordR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPasswordR.setForeground(new java.awt.Color(0, 102, 204));
        jLabelPasswordR.setText("Password :");
        getContentPane().add(jLabelPasswordR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabelCorreoR.setBackground(new java.awt.Color(255, 51, 0));
        jLabelCorreoR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCorreoR.setForeground(new java.awt.Color(0, 102, 204));
        jLabelCorreoR.setText("Correo Electronico :");
        getContentPane().add(jLabelCorreoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jButtonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(0, 102, 204));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 100, 30));

        jButtonCancelar.setBackground(new java.awt.Color(51, 153, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 102, 204));
        jButtonCancelar.setText("Iniciar Sesion");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        RegistroNombre.setBackground(new java.awt.Color(204, 204, 204));
        RegistroNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegistroNombre.setForeground(new java.awt.Color(51, 51, 51));
        RegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroNombreActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 200, 30));

        RegistroPassword.setBackground(new java.awt.Color(204, 204, 204));
        RegistroPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegistroPassword.setForeground(new java.awt.Color(51, 51, 51));
        RegistroPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 200, 30));

        RegistroCorreo.setBackground(new java.awt.Color(204, 204, 204));
        RegistroCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegistroCorreo.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(RegistroCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, 30));

        RegistroCodigo.setBackground(new java.awt.Color(204, 204, 204));
        RegistroCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegistroCodigo.setForeground(new java.awt.Color(51, 51, 51));
        RegistroCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 200, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registroT.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabelNombreR2.setBackground(new java.awt.Color(255, 51, 0));
        jLabelNombreR2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNombreR2.setForeground(new java.awt.Color(0, 102, 204));
        jLabelNombreR2.setText("Codigo:");
        getContentPane().add(jLabelNombreR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        getContentPane().add(jLabelFondoRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroPasswordActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        new IdentificacionUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void RegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroNombreActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // Toma el valor que ingresa en cada uno de los cuadros y los asigna a la variable
        if(ValidacionesIngreso()==false)
        {
            return;
        }

        if(RegistroCodigo.getText().length()<1 && RegistroNombre.getText().length()<1 && RegistroPassword.getText().length()<1 && RegistroCorreo.getText().length()<1)
        {
            return;
        }
    
        if(!RegistroCodigo.getText().isEmpty() && !RegistroNombre.getText().isEmpty() && !RegistroPassword.getText().isEmpty() && !RegistroCorreo.getText().isEmpty())
        {
            l = new ManejoUsuarios();        
            UsoUsuario=new Usuario();
            UsoUsuario.setCodigo(RegistroCodigo.getText());
            UsoUsuario.setNombre(RegistroNombre.getText());
            UsoUsuario.setClave(RegistroPassword.getText());
            UsoUsuario.setEmail(RegistroCorreo.getText());
            if (l.guardarUsuarios(UsoUsuario)){
                JOptionPane.showMessageDialog(null,"Usuario Grabado");     
                this.setVisible(false);
                new IdentificacionUsuario().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"El Usuario no se registro correctamente");     
            }
        }
        else
        {
           JOptionPane.showMessageDialog(null,"Ingrese todos los datos del usuario");     
        } 
//        if(new ManejarInicioSesion().RegistroIniciar(RegistroNombre.getText(), RegistroPassword.getText(), RegistroCorreo.getText()))
//            this.setVisible(false);
           
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void RegistroCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RegistroCodigo;
    private javax.swing.JTextField RegistroCorreo;
    private javax.swing.JTextField RegistroNombre;
    private javax.swing.JPasswordField RegistroPassword;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCorreoR;
    private javax.swing.JLabel jLabelFondoRegistro;
    private javax.swing.JLabel jLabelFondoRegistro1;
    private javax.swing.JLabel jLabelNombreR;
    private javax.swing.JLabel jLabelNombreR2;
    private javax.swing.JLabel jLabelPasswordR;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public ManejoUsuarios l;
    public Usuario UsoUsuario;

}
